apply plugin: 'java'
apply plugin: 'application'

sourceSets.main.resources.srcDirs = ["$rootDir/assets".toString()]
mainClassName = 'com.vancan.autofishing.lwjgl3.DesktopLauncher'
application.mainClass = mainClassName
eclipse.project.name = appName + '-lwjgl3'

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
}

jar {
    archiveBaseName = appName
    manifest { attributes 'Main-Class': mainClassName }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}
