buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies { classpath "com.mobidevelop.robovm:robovm-gradle-plugin:$robovmVersion" }
}

apply plugin: 'java'
apply plugin: 'robovm'

eclipse.project.name = appName + '-ios'
sourceSets.main.resources.srcDirs = ["$rootDir/assets".toString()]

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    implementation project(':core')
    implementation "com.mobidevelop.robovm:robovm-rt:$robovmVersion"
    implementation "com.mobidevelop.robovm:robovm-cocoatouch:$robovmVersion"
    implementation "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
}

robovm {
    // Points at robovm.xml / Info.plist.xml in this directory.
    iosSignIdentity = System.getenv('IOS_SIGN_IDENTITY')
    iosProvisioningProfile = System.getenv('IOS_PROVISIONING_PROFILE')
}
