[package]
name = "tjlocalizer-cli"
description = "Command-line front end for the Thanhtinz JAR Localizer."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "tjlocalizer"
path = "src/main.rs"

[dependencies]
tjlocalizer-core = { path = "../tjlocalizer-core" }
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
